spring.profiles.active=@activatedProperties@

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.application.name=Bootstrap Spring Boot

telegram.bot.name=BrokerTaxBot
telegram.bot.token=5080696657:AAEC0z8E2DAe-fve_JQiSEtGM2Ax47bcWpg