spring.profiles.active=@activatedProperties@

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.application.name=FreeDom Finance Broker Tax Calculation Service

spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username=aidar.m@salyqtez.kz
spring.mail.password=RY1sAMi3pu(u
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true