spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=

telegram.bot.name=salyqteztest_bot
telegram.bot.token=1978885491:AAFFO7RXbj37CbInofNkOArsQeIDb9znZdg
